version: 2

sources:
  - name: ethereum
    database: "{{ env_var('GOOGLE_PROJECT_ID', 'onchain-platform') }}"
    schema: raw

    tables:
      - name: blocks
      - name: transactions

  - name: polygon
    database: "{{ env_var('GOOGLE_PROJECT_ID', 'onchain-platform') }}"
    schema: polygon

    tables:
      - name: blocks
      - name: transactions
