network = "sepolia"
data-dir = "/home/user/nimbus-eth2/build/data"
jwt-secret = "/home/user/nimbus-eth2/build/data/jwt.hex"
node-name = "onchain"

[trustedNodeSync]
trusted-node-url = "https://beaconstate-sepolia.chainsafe.io"
backfill = true
reindex = true
