version: "3.9"

services:
  geth:
    image: ethereum/client-go:stable
    restart: always
    stop_grace_period: 1m
    volumes:
      - ./datadir/goerli:/datadir
    command: >
      --goerli
      --config /datadir/execution/config.toml
    ports:
      - 30303:30303
      - 8551:8551
      - 8545:8545
      - 9191:9191
    networks:
      - onchain-network

  beacon-node-sync:
    image: statusim/nimbus-eth2:amd64-v22.11.1
    volumes:
      - ./datadir/goerli:/home/user/nimbus-eth2/build/data
    command: >
      trustedNodeSync
      --config-file="/home/user/nimbus-eth2/build/data/consensus/node-sync-config.toml"
    networks:
      - onchain-network

  beacon:
    image: statusim/nimbus-eth2:amd64-v22.11.1
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - ./datadir/goerli:/home/user/nimbus-eth2/build/data
    command: >
      --config-file="/home/user/nimbus-eth2/build/data/consensus/config.toml"
      --web3-url="http://geth:8551"
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 127.0.0.1:5052:5052/tcp
      - 127.0.0.1:8008:8008/tcp
    depends_on:
      geth:
        condition: service_started
      beacon-node-sync:
        condition: service_completed_successfully
    networks:
      - onchain-network

networks:
  onchain-network:
    name: onchain-network
    driver: bridge

