apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2.5-alpine
        resources:
          limits:
            cpu: "200m"
            memory: "320Mi"
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: /data
            name: redis-data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: onchain
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: redis-external
  namespace: onchain
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      nodePort: 30379
      name: http-external