---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /data
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: local-pvc
    namespace: onchain
  hostPath:
    path: /data/local
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - microk8s-vm
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: onchain
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-pvc
    namespace: onchain
  hostPath:
    path: /data/redis
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - microk8s-vm
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: onchain
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ch-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: ch-pvc
    namespace: onchain
  hostPath:
    path: /data/clickhouse
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - microk8s-vm
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ch-pvc
  namespace: onchain
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi