from pulsar.schema import Record, Integer, String, Array


class Block(Record):
    number = Integer()
    hash = String()
    parent_hash = String()
    nonce = String()
    sha3_uncles = String()
    logs_bloom = String()
    transactions_root = String()
    state_root = String()
    receipts_root = String()
    difficulty = Integer()
    total_difficulty = Integer()
    extra_data = String()
    size = Integer()
    gas_limit = Integer()
    gas_used = Integer()
    base_fee_per_gas = Integer()
    timestamp = Integer()
    transactions_count = Integer()
    uncles = Array(String())

class Transaction(Record):
    hash = String()
    nonce = Integer()
    transaction_index = Integer()
    from = String()
    to = String()
    value = Integer()
    input = String()
    type = String()
    gas = Integer()
    gas_price = Integer()
    max_fee_pr_gas = Integer()
    max_priority_fee_per_gas = Integer()
    v = Integer()
    r = String()
    s = String()
    block_hash = String()
    block_number = Integer()
    block_timestamp = Integer()