apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-path-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k3d-main-agent-0
              - k3d-main-agent-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: test-local
#   labels:
#     name: test-local
# spec:
#   containers:
#   - name: app
#     image: busybox
#     command: ['sh', '-c', 'echo "The local volume is mounted!" > /mnt/test.txt && sleep 3600']
#     volumeMounts:
#       - name: local-persistent-storage
#         mountPath: /mnt
#   volumes:
#     - name: local-persistent-storage
#       persistentVolumeClaim:
#         claimName: local-path-pvc