client:
  service_url: pulsar://localhost:6650
consumer:
  topic: "onchain/${blockchain.coin}/${blockchain.data}"
  subscription_name: "${blockchain.coin}-${blockchain.data}-${hydra:job.id}"
  consumer_type: shared