defaults:
  - source: pulsar
  - sink: bigquery
  - worker: ray
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra logging
hydra:  
  output_subdir: null  
  run:  
    dir: .