network = "goerli"
data-dir = "/home/user/nimbus-eth2/build/data"
jwt-secret = "/home/user/nimbus-eth2/build/data/jwt.hex"
node-name = "onchain"

[trustedNodeSync]
trusted-node-url = "https://goerli.beaconstate.info"
backfill = true
reindex = true
