apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: blockchain.ethereum.block
  namespace: onchain
  labels:
    strimzi.io/cluster: onchain
spec:
  partitions: 4
  replicas: 2
  config:
    retention.ms: 900000
    segment.bytes: 1000000

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: blockchain.ethereum.blocknumber
  namespace: onchain
  labels:
    strimzi.io/cluster: onchain
spec:
  partitions: 4
  replicas: 2
  config:
    retention.ms: 900000
    segment.bytes: 1000000