apiVersion: v1
kind: Pod
metadata:
  name: nats-box
  namespace: onchain
spec:
  containers:
    - image: natsio/nats-box:latest
      name: test
      command: ["sleep", "infinity"]
      resources:
        limits:
          cpu: 200m
          memory: 384Mi
        requests:
          cpu: 200m
          memory: 384Mi
  # nodeSelector:
  #   type: workload
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: type
  #           operator: In
  #           values:
  #           - workload
  # tolerations:
  # - effect: NoSchedule
  #   key: type
  #   operator: Equal
  #   value: workload
  # - effect: NoExecute
  #   key: type
  #   operator: Equal
  #   value: workload
  # - effect: PreferNoSchedule
  #   key: load
  #   operator: Equal
  #   value: low