apiVersion: v1
kind: Pod
metadata:
  name: proton
  namespace: onchain
spec:
  containers:
    - image: ghcr.io/timeplus-io/proton:latest
      name: proton
      # command: ["sleep", "infinity"]
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: onchain
spec:
  volumes:
    - name: test
      hostPath:
        path: /data
        type: Directory
  containers:
    - image: python:3.11
      name: test
      command: ["sleep", "infinity"]
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 512Mi
      volumeMounts:
        - name: test
          mountPath: /data

  # nodeSelector:
  #   type: workload
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: type
  #           operator: In
  #           values:
  #           - workload
  # tolerations:
  # - effect: NoSchedule
  #   key: type
  #   operator: Equal
  #   value: workload
  # - effect: NoExecute
  #   key: type
  #   operator: Equal
  #   value: workload
  # - effect: PreferNoSchedule
  #   key: load
  #   operator: Equal
  #   value: low